# Generated by Django 2.2.4 on 2020-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=10)),
                ('sales', models.CharField(max_length=10)),
            ],
        ),
    ]
